# Generated by Django 4.1.5 on 2023-02-03 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_book_cover'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='Book',
        ),
    ]
